# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGODB_USER: auth 
      MONGODB_PASS: auth
    ports: 
      - 27017:27017
